language: python
python:
- '3.6'
cache: pip
install:
- pip install --upgrade pip setuptools
- pip install coveralls
- pip install flake8
- pip install .
script:
- python setup.py test
- flake8 vyper/ tests/
sudo: required
services:
- docker
after_success:
- coveralls
- openssl aes-256-cbc -K $encrypted_6ed035d313c9_key -iv $encrypted_6ed035d313c9_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
deploy:
  skip_cleanup: true
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c
    "apt update -qq && cd $(pwd) &&
    snapcraft && snapcraft push *.snap --release edge"
  on:
    branch: master
