language: python

python:
  - "3.6"

cache: pip

install:
  - pip install --upgrade pip setuptools
  - pip install coveralls
  - pip install .

script:
  - python setup.py test

after_success:
- coveralls
