name: Release

on:
  release:
    types: [published]
  repository_dispatch: []

jobs:
  snapcraft:

    runs-on: ubuntu-latest

    steps:
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install snapcraft

    - name: Build Snap
      run: snapcraft --destructive-mode

    - name: Login to Snapcraft
      run: echo "${{ secrets.SNAPCRAFT_TOKEN }}" | snapcraft login --with -

    - name: Push Snap
      run: snapcraft push vyper*.snap
